version: '3'
services:
  bar:
    container_name: bar
    image: nahoo408/bar_app:latest
    networks:
      - all
    ports:
      - 8001:8080
  kitchen:
    container_name: kitchen
    image: dotbinh/kitchen-app:latest
    networks:
      - all
    ports:
      - 8002:8000
  diner:
    container_name: diner
    environment:
      - diner.bar.url=http://bar:8080
      - diner.kitchen.url=http://kitchen:8000
    image: rwsen/diner-image:latest
    networks:
      - all
    ports:
      - 8000:8080
    depends_on:
      - bar
      - kitchen

networks:
  all:
